### ISSUE TITLE
[bug] 内存溢出导致软件闪退

### ISSUE THREAD

**Issue by moonbai** [gkd-kit/gkd#115]
Generated by AppErrorsTracking
Project Url: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Redmi
[Device Model]: 22081212C
[Display]: TKQ1.220829.002 test-keys
[Android Version]: 13
[Android API Level]: 33
[System Locale]: zh_CN
[Process ID]: 18052
[CPU ABI]: arm64-v8a
[Package Name]: li.songe.gkd
[Version Name]: 1.2.1
[Version Code]: 6
[Error Type]: JVM
[Crash Time]: 2023-10-06T20:53:14.805
[Stack Trace]:
java.lang.OutOfMemoryError: Failed to allocate a 208 byte allocation with 286216 free bytes and 279KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at android.view.accessibility.AccessibilityCache.getNode(AccessibilityCache.java:344)
	at android.view.accessibility.AccessibilityInteractionClient.findAccessibilityNodeInfoByAccessibilityId(AccessibilityInteractionClient.java:541)
	at android.view.accessibility.AccessibilityNodeInfo.getChild(AccessibilityNodeInfo.java:1221)
	at android.view.accessibility.AccessibilityNodeInfo.getChild(AccessibilityNodeInfo.java:1190)
	at li.songe.gkd.service.AbExtKt$abTransform$3$1.invokeSuspend(AbExt.kt:103)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at li.songe.selector.Transform$8$1.invokeSuspend(Transform.kt:57)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at li.songe.selector.Transform$querySelectorAll$1$1.invokeSuspend(Transform.kt:104)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:168)
	at li.songe.selector.Transform$querySelector$1.invoke(Transform.kt:86)
	at li.songe.selector.Transform$querySelector$1.invoke(Transform.kt:83)
	at li.songe.gkd.service.AbExtKt.querySelector(AbExt.kt:60)
	at li.songe.gkd.data.Rule.query(Rule.kt:61)
	at li.songe.gkd.service.GkdAbService$1$8.invokeSuspend(GkdAbService.kt:182)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e917b28, Dispatchers.Default]

![Screenshot_2023-10-06-20-54-02-517_com.fankes.apperrorstracking.jpg](https://github.com/gkd-kit/gkd/assets/34854875/27e22c39-c33c-488a-b25a-b59248c15827)

**Comment by lisonge** [comment]
试试下面这个版本还会出现吗？

github files: [release.zip](https://github.com/gkd-kit/gkd/files/12833181/release.zip) 

或者蓝奏云: <https://lisonge.lanzouy.com/b06e2uh7c > 密码: `gkd`

**Comment by moonbai** [comment]
> 试试下面这个版本还会出现吗？
> 
> github files: [release.zip](https://github.com/gkd-kit/gkd/files/12833181/release.zip) 
> 
> 或者蓝奏云: <https://lisonge.lanzouy.com/b06e2uh7c > 密码: `gkd`
> 

.我试用一段时间看看

**Comment by lisonge** [comment]
https://github.com/gkd-kit/gkd/releases/tag/v1.3.0

试试 v1.3.0 呢

**Comment by lisonge** [comment]
请问怎么样了

**Comment by moonbai** [comment]
> 请问怎么样了

截止目前未发生闪退问题
