### ISSUE TITLE
ColorOS12 开启无障碍后，APP崩溃

### ISSUE THREAD

**Issue by dlh996** [gkd-kit/gkd#426]
### 日志文件

```
2023-12-27 22:07:16.290 28800-29394 AndroidRuntime          li.songe.gkd.debug                   E  FATAL EXCEPTION: pool-4-thread-1
                                                                                                    Process: li.songe.gkd.debug, PID: 28800
                                                                                                    java.lang.IllegalStateException: Cannot perform this action on a not sealed instance.
                                                                                                    	at android.view.accessibility.AccessibilityRecord.enforceSealed(AccessibilityRecord.java:758)
                                                                                                    	at android.view.accessibility.AccessibilityRecord.getSource(AccessibilityRecord.java:192)
                                                                                                    	at li.songe.gkd.service.GkdAbService$1$4.invoke$lambda$0(GkdAbService.kt:211)
                                                                                                    	at li.songe.gkd.service.GkdAbService$1$4.$r8$lambda$oHqBvxXtReCEjKr9yx3N2mRAfBg(Unknown Source:0)
                                                                                                    	at li.songe.gkd.service.GkdAbService$1$4$$ExternalSyntheticLambda0.run(Unknown Source:24)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:920)
```

### Bug 描述

代码版本：fix: 子孙节点遍历顺序错误 lisonge Today 12:38 032ce0fc

打包在ColorOS12上，开启无障碍后，直接崩了。。。
日志是debug版本的日志。

**Comment by lisonge** [comment]
试试这个呢 

https://github.com/gkd-kit/gkd/actions/runs/7339276541

**Comment by dlh996** [comment]
> 试试这个呢
> 
> https://github.com/gkd-kit/gkd/actions/runs/7339276541

这个可以。大佬辛苦

**Comment by dlh996** [comment]
1.5.4没问题。1,6,0不行。上午没带那个手机，没有试。

**Comment by iloveskiff** [comment]
1.6.0华为手机也出现开启无障碍app崩溃问题
日志：https://github.com/gkd-kit/inspect/files/13786977/file.zip

**Comment by lisonge** [comment]
使用 v1.6.2 试试

**Comment by dlh996** [comment]
1.6.2 没问题了。刚试了
