### ISSUE TITLE
TextField使用微信输入法清空功能，应用ANR最终崩溃

### ISSUE THREAD

**Issue by Supremesir** [gkd-kit/gkd#485]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题

### 日志文件

FATAL EXCEPTION: main
                                        Process: li.songe.gkd.debug, PID: 27301
                                        java.lang.RuntimeException: Error while applying EditCommand batch to buffer (length=8, composition=null, selection=TextRange(8, 8)):
                                         > DeleteSurroundingTextInCodePointsCommand(lengthBeforeCursor=2147483647, lengthAfterCursor=2147483647)
                                        	at androidx.compose.ui.text.input.EditProcessor.apply(EditProcessor.kt:117)
                                        	at androidx.compose.foundation.text.TextFieldDelegate$Companion.onEditCommand$foundation_release(TextFieldDelegate.kt:194)
                                        	at androidx.compose.foundation.text.TextFieldDelegate$Companion$restartInput$1.invoke(TextFieldDelegate.kt:254)
                                        	at androidx.compose.foundation.text.TextFieldDelegate$Companion$restartInput$1.invoke(TextFieldDelegate.kt:251)
                                        	at androidx.compose.ui.text.input.TextInputServiceAndroid$createInputConnection$1.onEditCommands(TextInputServiceAndroid.android.kt:135)
                                        	at androidx.compose.ui.text.input.RecordingInputConnection.endBatchEditInternal(RecordingInputConnection.android.kt:157)
                                        	at androidx.compose.ui.text.input.RecordingInputConnection.addEditCommandWithBatch(RecordingInputConnection.android.kt:131)
                                        	at androidx.compose.ui.text.input.RecordingInputConnection.deleteSurroundingTextInCodePoints(RecordingInputConnection.android.kt:198)
                                        	at android.view.inputmethod.RemoteInputConnectionImpl.lambda$deleteSurroundingTextInCodePoints$32(RemoteInputConnectionImpl.java:930)
                                        	at android.view.inputmethod.RemoteInputConnectionImpl.$r8$lambda$7MVH5PJa88NFqzwFT1IK2b8TYt4(Unknown Source:0)
                                        	at android.view.inputmethod.RemoteInputConnectionImpl$$ExternalSyntheticLambda2.run(Unknown Source:8)
                                        	at android.os.Handler.handleCallback(Handler.java:958)
                                        	at android.os.Handler.dispatchMessage(Handler.java:99)
                                        	at android.os.Looper.loopOnce(Looper.java:224)
                                        	at android.os.Looper.loop(Looper.java:318)
                                        	at android.app.ActivityThread.main(ActivityThread.java:8754)
                                        	at java.lang.reflect.Method.invoke(Native Method)
                                        	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
                                        	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
                                        Caused by: java.lang.StringIndexOutOfBoundsException: length=0; index=2147483639
                                        	at java.lang.String.charAt(Native Method)
                                        	at androidx.compose.ui.text.input.PartialGapBuffer.get(GapBuffer.kt:326)
                                        	at androidx.compose.ui.text.input.EditingBuffer.get$ui_text_release(EditingBuffer.kt:125)
                                        	at androidx.compose.ui.text.input.DeleteSurroundingTextInCodePointsCommand.applyTo(EditCommand.kt:344)
                                        	at androidx.compose.ui.text.input.EditProcessor.apply(EditProcessor.kt:114)
                                        	at androidx.compose.foundation.text.TextFieldDelegate$Companion.onEditCommand$foundation_release(TextFieldDelegate.kt:194) 
                                        	at androidx.compose.foundation.text.TextFieldDelegate$Companion$restartInput$1.invoke(TextFieldDelegate.kt:254) 
                                        	at androidx.compose.foundation.text.TextFieldDelegate$Companion$restartInput$1.invoke(TextFieldDelegate.kt:251) 
                                        	at androidx.compose.ui.text.input.TextInputServiceAndroid$createInputConnection$1.onEditCommands(TextInputServiceAndroid.android.kt:135) 
                                        	at androidx.compose.ui.text.input.RecordingInputConnection.endBatchEditInternal(RecordingInputConnection.android.kt:157) 
                                        	at androidx.compose.ui.text.input.RecordingInputConnection.addEditCommandWithBatch(RecordingInputConnection.android.kt:131) 
                                        	at androidx.compose.ui.text.input.RecordingInputConnection.deleteSurroundingTextInCodePoints(RecordingInputConnection.android.kt:198) 
                                        	at android.view.inputmethod.RemoteInputConnectionImpl.lambda$deleteSurroundingTextInCodePoints$32(RemoteInput

### Bug 描述

> 首先，我感觉这应该是个Compose底层的bug。

具体问题视频如下，在使用了TextField的地方，输入一些文字，然后使用微信输入法的清空功能，这时候会导致应用ANR，最终崩溃。
![image](https://github.com/gkd-kit/gkd/assets/32538902/6796ba63-a934-4d76-b318-456b9131b8e7)
![video](https://github.com/gkd-kit/gkd/assets/32538902/47f986a0-7bd4-4452-a482-e445b7adf0cc)

经过一顿搜索，发现貌似是Compose的底层bug，不过触发的场景都是Android TV系统上的clear按键，而且官方标记为fixed
https://android-review.googlesource.com/c/platform/frameworks/support/+/2483915
https://issuetracker.google.com/issues/228862731

按照Compose发版节奏来看，项目里的1.5.4版本应该已经包含了相关的修复代码，不过目前仍然稳定复现。尝试提升版本到最新的1.6.0-rc1还是不能解决问题。

不知道开发者有没有办法暂时规避这个问题，或者提交给Google等待修复？

**Comment by lisonge** [comment]
请问其它基于 compose 的的应用是否存在此问题？

**Comment by lisonge** [comment]
比如 <https://github.com/easybangumiorg/EasyBangumi>

**Comment by Supremesir** [comment]
> 请问其它基于 compose 的的应用是否存在此问题？

我写了demo也是有这个问题的😂不知道其他基于compose的知名应用有没有这问题

**Comment by Supremesir** [comment]
> 比如 <https://github.com/easybangumiorg/EasyBangumi>

试了下都是复现的，不知道微信输入法怎么实现的清空功能，又触发了compose的新bug里。

**Comment by lisonge** [comment]
我使用的百度输入法，并没有清空这个功能，百度输入法里想要实现此功能有两种方式

- 长按删除键，相当于连续点按删除键
- 使用它的工具操作，全选-删除

**Comment by lisonge** [comment]
看起来是 compose 或者 微信输入法 的问题，我这边不准备解决
