### ISSUE TITLE
跳过时报错，提示“Cannot perform this operationbecause the connection pool has been closed”

### ISSUE THREAD

**Issue by Matrix-bak** [gkd-kit/gkd#533]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] 检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题

- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-不包含日志将会被直接关闭

https://github.com/gkd-kit/inspect/files/14443754/file.zip

### BUG描述及其复现步骤(视频/截图)

![Screenshot_20240229_142720](https://github.com/gkd-kit/gkd/assets/65644040/41808170-5355-4e1a-b114-f289cf94eac3)
![Screenshot_20240229_142712](https://github.com/gkd-kit/gkd/assets/65644040/1b7973b3-a6af-437b-b3fc-a056d48cb8ad)

**Comment by lisonge** [comment]
日志文件缺失

**Comment by lisonge** [comment]
看起来是 android-room 的问题，麻烦重启应用后试试

**Comment by lisonge** [comment]
如果在3天内没有回复则关闭此 issue

**Comment by lisonge** [comment]
```txt
java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
	at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:1071)
	at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:685)
	at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:380)
	at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:896)
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
	at s3.h.a0(Unknown Source:2)
	at androidx.room.k.insertAndReturnIdsList(SourceFile:5)
	at li.songe.gkd.data.ClickLog_TriggerLogDao_Impl$insert$2.call(SourceFile:3)
	at li.songe.gkd.data.ClickLog_TriggerLogDao_Impl$insert$2.call(SourceFile:1)
	at androidx.room.h.invokeSuspend(Unknown Source:8)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:128)
	at f.m0.run(Unknown Source:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
```

我不知道为什么数据库被关闭，而且我的手机无法复现这个问题

另外我使用 Google/Github 搜索相关的问题都没有 有效的解决方案

重启应用应该可以解决，如果实在影响使用建议换个设备或者卸载
