### ISSUE TITLE
Android 14 导入在线链接订阅解析失败

### ISSUE THREAD

**Issue by Leon406** [gkd-kit/gkd#599]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
- [X] GKD 默认不包含任何规则, 如果您想要自定义规则, 您可以 [查看文档](https://gkd.li/)
- [X] 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
- [X] 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题

### 日志文件-无论什么问题不包含日志将会被直接关闭

https://github.com/gkd-kit/inspect/files/14993995/file.zip

### BUG描述(文字/截图/视频)

Android 14（澎湃OS）手机导入订阅后，提示解析失败

换到Android 12（MIUI 14）的手机是可以正常解析的

测试订阅： https://registry.npmmirror.com/gkd-subscription/latest/files

### 期望行为(文字/截图/视频)

正常解析在线订阅

### 实际行为(文字/截图/视频)

订阅解析失败

**Comment by lisonge** [comment]
> Android 14（澎湃OS）手机导入订阅后，提示解析失败

在我的 Android 14（澎湃OS）无法复现，提示解析成功

---

日志里的错误是
```txt
U1.c: Found character '<' instead of '{' while looking for the start of an object
	at V1.k.e(Unknown Source:66)
	at T1.c.b(Unknown Source:43)
	at T1.c.a(Unknown Source:154)
	at li.songe.gkd.util.Json5Kt.json5ToJson(Unknown Source:54)
	at li.songe.gkd.data.RawSubscription$Companion.parse(Unknown Source:7)
	at li.songe.gkd.data.RawSubscription$Companion.parse$default(Unknown Source:5)
	at li.songe.gkd.ui.home.HomeVm$addSubsFromUrl$1.invokeSuspend(Unknown Source:222)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:128)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(Unknown Source:3)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(Unknown Source:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Unknown Source:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:0)
```
看起来是你的 json5 字符串有问题

你有尝试其它链接输入吗？比如

```txt
https://registry.npmmirror.com/gkd-subscription/latest/files/dist/gkd.json5
```
```txt
https://fastly.jsdelivr.net/npm/gkd-subscription@latest/dist/gkd.json5
```

**Comment by lisonge** [comment]
[app-release.zip](https://github.com/gkd-kit/gkd/files/14997022/app-release.zip)

可以使用这个版本复现一遍问题后再把日志发过来看看

**Comment by Leon406** [comment]
感谢，编译debug代码，找到问题了

生成的链接二维码有问题，后面多了不见字符

![image](https://github.com/gkd-kit/gkd/assets/26186607/92a21d38-f75c-41d7-94fb-a67e308cf21b)

**Comment by Leon406** [comment]
生成url中多余的符号是不可打印字符 ASCII 码 0

扫码软件做了处理，点击链接可以正常打开
