### ISSUE TITLE
[BUG] 规则无法加载

### ISSUE THREAD

**Issue by Matrix-bak** [gkd-kit/gkd#710]
### 一些验证

- [X] 请 **确保** 您已经查阅了 [GKD 官方文档](https://gkd.li)  以及 [常见问题](https://gkd.li/guide/faq)
- [X] 1.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 2.请 **确保** [已有的问题](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
- [X] 3.请 **不要** 开启重复相关的 issue，这将导致别人搜索 issue 时出现无关的低质量信息, 否则你的问题将会被直接关闭甚至删除
- [X] 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
- [X] 请 **确保** 你的问题能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题)
- [X] 请 **确保** 提供下列的日志和BUG描述及其复现步骤, 否则你的问题将会被直接关闭

### 日志文件-无论什么问题不包含日志将会被直接关闭

[log-1723796862081.zip](https://github.com/user-attachments/files/16634878/log-1723796862081.zip)

### BUG描述(文字/截图/视频)

订阅界面无法加载规则
![Screenshot_20240816_162748](https://github.com/user-attachments/assets/993bcd45-94a4-48e2-832d-69ac58f5f695)

### 期望行为(文字/截图/视频)

订阅显示正常

### 实际行为(文字/截图/视频)

订阅无法正常显示

**Comment by lisonge** [comment]
在 `2024-08-15-21:35:27.808` gkd 发生了重启，此后数据库发生连接错误

我不知道(也不能复现)为什么在某些设备上会有数据库无法打开的错误

```txt
android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14 SQLITE_CANTOPEN): , while compiling: PRAGMA journal_mode
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1102)
	at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:819)
	at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:420)
	at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:350)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:273)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:220)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:918)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:898)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:762)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:751)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:373)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
```

这个东西我不能复现无法解决，你可以尝试强制结束应用后重启 gkd
