### ISSUE TITLE
[BUG] 订阅消失

### ISSUE THREAD

**Issue by yanmuq** [gkd-kit/gkd#736]
### 日志文件

https://f.gkd.li/17008407

### BUG描述(文字/截图/视频)

在线订阅突然全部消失，只剩本地订阅。猜测可能是被系统清理垃圾清理掉？

### 期望行为(文字/截图/视频)

不消失

### 实际行为(文字/截图/视频)

消失

**Comment by lisonge** [comment]
需要重启应用后的订阅列表界面截图

**Comment by lisonge** [comment]
![image](https://github.com/user-attachments/assets/cba05996-8e0e-456c-9bb9-29ead076ed1e)

从日志看你的订阅已经生效了

**Comment by yanmuq** [comment]
本来我有2个在线订阅，今天早上发现不跳广告了，进入这个界面只剩本地订阅。我下午反馈时已经重新添加订阅了

**Comment by yanmuq** [comment]
也就是订阅消失发生在今天早上及更早的时候

**Comment by lisonge** [comment]
看了一下，你的日志只有 09-14 之后的，第一次启动也是在 09-14 10:22:10

09-14 10:22:10 有一次更新检测但是没有任何输出，说明没有远程订阅

为什么没有 09-13 的日志？是第一次安装还是卸载了之后再安装的？

**Comment by yanmuq** [comment]
我用了很久了，那可能就发生在13号？此版本自动更新后没有重新安装过

**Comment by yanmuq** [comment]
存在被垃圾清理删除的可能吗？我手机品牌是华为，有应用无损压缩功能

**Comment by lisonge** [comment]
这个我不知道了，无法排查了

**Comment by yanmuq** [comment]
https://f.gkd.li/17055793，今天手机重启后订阅数据恢复，原来的配置和订阅都恢复了，这是新的日志

**Comment by lisonge** [comment]
![image](https://github.com/user-attachments/assets/15ded093-dc85-4165-b6d6-e7ce344306ac)

我好奇日志为什么会多出这些数据库，多数据库是几乎1年前的版本了，你是有做什么数据操作吗？或者安装了什么旧版本吗？

**Comment by yanmuq** [comment]
完全没有，就很奇怪，更新也是自动检测更新，我更了，没有进行其他操作

**Comment by lisonge** [comment]
你可以尝试卸载后重新安装看看

关于数据备份：订阅列表长按全选后右上角保存，重新安装后右上角导入数据

**Comment by yanmuq** [comment]
目前是正常的啊，为什么重新安装，以防这个问题再次出现吗

**Comment by bleach2012** [comment]
我今天也遇到这样的问题了，因为广告不跳才点开看的，发现之前的订阅都没了……

**Comment by yanmuq** [comment]
> 我今天也遇到这样的问题了，因为广告不跳才点开看的，发现之前的订阅都没了……

你是什么型号的手机

**Comment by yanmuq** [comment]
> 我今天也遇到这样的问题了，因为广告不跳才点开看的，发现之前的订阅都没了……

你用的是什么手机

**Comment by bleach2012** [comment]
> > 我今天也遇到这样的问题了，因为广告不跳才点开看的，发现之前的订阅都没了……
> 
> 你用的是什么手机

小米9

**Comment by mailshuxin** [comment]
我的也是这个问题，三星S25 ultra

**Comment by BG2NDR** [comment]
[log-1774338679927.zip](https://github.com/user-attachments/files/26205437/log-1774338679927.zip)

+1
机型是SamsungGalaxyS24
oneui7
一觉起来就全失效了
且无法导入任何新订阅
导出日志后自动恢复 手动重新打开订阅开关

**Comment by yanmuq** [comment]
> [log-1774338679927.zip](https://github.com/user-attachments/files/26205437/log-1774338679927.zip)
> 
> +1 机型是SamsungGalaxyS24 oneui7 一觉起来就全失效了 且无法导入任何新订阅 导出日志后自动恢复 手动重新打开订阅开关

这种最难抓了，偶发，没日志，抓不到也就修不了，没招

**Comment by Lin-arm** [comment]
> [log-1774338679927.zip](https://github.com/user-attachments/files/26205437/log-1774338679927.zip)
> 
> +1 机型是SamsungGalaxyS24 oneui7 一觉起来就全失效了 且无法导入任何新订阅 导出日志后自动恢复 手动重新打开订阅开关



<details>
<summary>gkd-20260324.log 片段</summary>

```ts
09:32:55.067 A11yFeat, DefaultDispatcher-worker-1, a11y.useRuleChangedLog(A11yFeat.kt:271)
[0]: TopActivity(appId=com.tencent.mm, activityId=null, number=0)
[1]: id:667, v:445, type:app, gKey=10, gName:开屏广告-微信小程序, index:0, key:null, status:ok
[2]: id:667, v:445, type:app, gKey=25, gName:局部广告-订阅号消息-推荐文章, index:0, key:null, status:ok
[3]: id:667, v:445, type:app, gKey=28, gName:分段广告-订阅号消息-视频推荐, index:0, key:0, status:ok
[4]: id:667, v:445, type:app, gKey=28, gName:分段广告-订阅号消息-视频推荐, index:1, key:1, status:需要提前触发某个规则
[5]: id:667, v:445, type:app, gKey=28, gName:分段广告-订阅号消息-视频推荐, index:2, key:2, status:需要提前触发某个规则
[6]: id:667, v:445, type:app, gKey=30, gName:全屏广告-文档页面-腾讯文档APP弹窗, index:0, key:null, status:ok
[7]: id:667, v:445, type:app, gKey=31, gName:分段广告-订阅号消息-推荐阅读, index:0, key:0, status:ok
[8]: id:667, v:445, type:app, gKey=31, gName:分段广告-订阅号消息-推荐阅读, index:1, key:1, status:需要提前触发某个规则
[9]: id:667, v:445, type:app, gKey=31, gName:分段广告-订阅号消息-推荐阅读, index:2, key:2, status:需要提前触发某个规则
[10]: id:667, v:445, type:app, gKey=35, gName:分段广告-公众号文章内广告, index:0, key:0, status:ok
[11]: id:667, v:445, type:app, gKey=35, gName:分段广告-公众号文章内广告, index:1, key:20, status:需要提前触发某个规则
[12]: id:667, v:445, type:app, gKey=35, gName:分段广告-公众号文章内广告, index:2, key:25, status:需要提前触发某个规则
[13]: id:667, v:445, type:app, gKey=35, gName:分段广告-公众号文章内广告, index:3, key:50, status:需要提前触发某个规则
[14]: id:667, v:445, type:app, gKey=37, gName:全屏广告-小程序弹窗广告, index:0, key:null, status:ok
[15]: id:667, v:445, type:app, gKey=38, gName:功能类-自动语音转文字, index:0, key:null, status:ok

09:32:56.002 A11yState, pool-5-thread-1, a11y.updateTopActivity(A11yState.kt:236)
com.tencent.mm/null/0 -> com.sec.android.app.launcher/.Launcher/0 (scene=A11y)

09:32:57.446 A11yState, pool-5-thread-1, a11y.updateTopActivity(A11yState.kt:236)
com.sec.android.app.launcher/.Launcher/0 -> com.sec.android.app.launcher/.Launcher/1 (scene=A11y)

09:32:58.123 A11yService, main, service.A11yService.onReceive(A11yService.kt:80)
screenStateReceiver->android.intent.action.SCREEN_OFF

09:32:58.250 A11yState, pool-5-thread-1, a11y.updateTopActivity(A11yState.kt:236)
com.sec.android.app.launcher/.Launcher/1 -> com.android.systemui/null/0 (scene=A11y)

10:08:52.697 App, main, App.onCreate(App.kt:174)

10:08:52.723 LifecycleCallbacks, main, service.A11yService.<init>(A11yService.kt:100)
onCreated -> SelectToSpeakService

10:08:52.737 LifecycleCallbacks, main, service.A11yService.<init>(A11yService.kt:100)
onA11yConnected -> SelectToSpeakService

10:08:53.240 CoroutineExt, DefaultDispatcher-worker-5, util.launchTry(CoroutineExt.kt:27)
android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/storage/emulated/0/Android/data/li.songe.gkd/files/db/gkd.db' with flags 0x30000000: Unable to deduct failure reason
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:412)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:244)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:765)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:299)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:266)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:1679)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:1616)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1257)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:476)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:419)
	at m6.f.d(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:76)
	at m6.f.b(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:24)
	at m6.g.r0(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:10)
	at k4.f.b(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:107)
	at a0.z1.b(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:993)
	at wb.p.getValue(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:21)
	at b6.t.W(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:31)
	at z5.r.k(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:9)
	at a0.q.B(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:620)
	at a0.q.p(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:189)
	at t3.a.u(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:19)
	at nf.a0.M(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:46)
	at a0.v.B(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:708)
	at a0.v.p(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:137)
	at a0.v.B(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:1683)
	at a0.v.p(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:358)
	at nf.a.A0(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:39)
	at nf.a0.A(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:24)
	at androidx.lifecycle.q.B(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:1055)
	at cc.a.n(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:9)
	at nf.j0.run(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:115)
	at nf.u0.y0(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:77)
	at nf.a0.F(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:99)
	at lg.d5.b(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:101)
	at wg.c.B(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:152)
	at wg.c.p(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:35)
	at yg.x.B(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:38)
	at cc.a.n(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:9)
	at nf.j0.run(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:115)
	at n.i.run(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:35)
	at uf.j.run(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:3)
	at uf.a.run(r8-map-id-50ac8dd4cea93521370c6d6c095cc4319ed8068fc9a95c88bd9ac4934febe403:88)
Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN[14]): Could not open database
	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:374)
	... 41 more


10:08:53.244 Toast, DefaultDispatcher-worker-5, util.launchTry(CoroutineExt.kt:29)
Cannot open database '/storage/emulated/0/Android/data/li.songe.gkd/files/db/gkd.db' with flags 0x30000000: Unable to deduct failure reason

10:08:53.737 Toast, main, App.onCreate(App.kt:176)
Cannot open database '/storage/emulated/0/Android/data/li.songe.gkd/files/db/gkd.db' with flags 0x30000000: Unable to deduct failure reason
```

</details>

时间点： 10:08:53.240 
报错： `Cannot open database '/storage/emulated/0/Android/data/li.songe.gkd/files/db/gkd.db' with flags 0x30000000: Unable to deduct failure reason` 
大致意思是 没法打开数据库，问的豆包是这样说的

<img width="1156" height="600" alt="Image" src="https://github.com/user-attachments/assets/de4e8efc-c1b0-4ca4-b0f8-508d1d0f9046" />


可惜日志里的数据库文件 gkd.db 应该是新创建的，而不是出问题那会的。
看日志里的订阅文件有6条，但 gkd.db 的 subs_item 表里只有两条订阅记录，ctime 全称应该是 `create time (创建时间)` ，换算后显然是出问题之后新创建的。
<img width="1439" height="546" alt="Image" src="https://github.com/user-attachments/assets/a3e18a9a-a78e-4402-8ffc-2e661d2dc033" />

**Comment by BG2NDR** [comment]
更新
机型是SamsungGalaxyS24
oneui7
一觉起来就全失效了
且无法导入任何新订阅
这次还没恢复就导出日志了

[log-1774698975066.zip](https://github.com/user-attachments/files/26322967/log-1774698975066.zip)
这个是刚出问题的log
[log-1774699385132.zip](https://github.com/user-attachments/files/26323015/log-1774699385132.zip)
这个是尝试导入之后的log（导入了也没反应）
